location        = "eastus"
rg_name         = "arc-demo-rg"
aks_name        = "arcaksdemo"
dns_prefix      = "arcaksdemo"
# github_app_id   = "123456"
# github_app_installation_id = "654321"
# github_app_private_key     = "<PEM CONTENTS>"
