apiVersion: actions.github.com/v1alpha1
kind: AutoScalingRunnerSet
metadata:
  name: arc-usisng-system-runners
  namespace: arc
spec:
  githubConfigUrl: https://github.com/Sensini7/arc-aks
  githubConfigSecret: github-config
  minRunners: 0
  maxRunners: 10
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
