name: Deploy GitHub ARC Infra

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: 1.7.5

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AZURE_AKS }} --admin --overwrite-existing

    - name: Apply Runner ScaleSet Manifest
      run: kubectl apply -f manifests/arc-autoscale-runner.yaml
